name: Test

on:
  pull_request:
    types: [synchronize, opened, reopened, edited]
  workflow_dispatch:

jobs:
  main:
    name: Build & Run Tests
    runs-on: macOS-15
    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: Select Xcode 26
        run: sudo xcode-select -s /Applications/Xcode_26.0.app

      - name: Run tests
        run: swift test